[workspace]
members = [
    "apps/client",
    "apps/controller",
    "apps/runner",
    "libs/cargo_manifest",
    "libs/compiler",
    "libs/core_actor",
    "libs/core_log",
    "libs/core_ui",
    "libs/interop",
    "libs/lxd",
    "libs/process",
    "libs/sandbox",
]
