[workspace]
members = [
    "apps/client",
    "apps/controller",
    "apps/runner",
    "libs/actor",
    "libs/compiler",
    "libs/interop",
    "libs/log",
    "libs/lxd",
    "libs/process",
    "libs/sandbox",
]
