[package]
name = "client"
version = "0.1.0"
authors = ["Patryk Wychowaniec <wychowaniec.patryk@gmail.com>"]
edition = "2018"

[dependencies]
colored = "1.9"
lib_log = { path = "../../libs/log" }
lib_protocol = { path = "../../libs/protocol" }
prettytable-rs = "0.8"
semver = { version = "0.9", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
snafu = "0.6"
structopt = "0.3"
tokio = "=0.2.0-alpha.6"
tonic = "0.1.0-alpha.6"
uuid = { version = "0.8", features = ["v4"] }