[package]
name = "controller"
version = "0.1.0"
authors = ["Patryk Wychowaniec <wychowaniec.patryk@gmail.com>"]
edition = "2018"

[dependencies]
bastion = "0.3"
bytes = "0.4"
lib_log = { path = "../../libs/log" }
lib_protocol = { path = "../../libs/protocol" }
prost = "0.5"
prost-derive = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
snafu = "0.6"
tokio = "=0.2.0-alpha.6"
tonic = "0.1.0-alpha.6"